### ISSUE TITLE
deployfile.yaml paths should be relative to deployfile dir

### ISSUE THREAD

**Issue by miraculixx** [omegaml/omegaml#461]
*Currently*

* paths in deployfile.yaml are relative to the current working directory (cwd)
  (where `$ om runtime deploy` is invoked)
* this is confusing as the command works when the (cwd) is the same as the 
  where the deployfile is, but does not when the deployfile is given via
  `$ om runtime deploy --specs /other/path/to/deployfile.yaml`

*Expected*

1. temporarily set the cwd to dirname(/path/to/deployfile.yaml) before running commands
2. explain in docs

*Workaround*

* this can be simulated by using a variable with a global path
* the path can be overriden by using `$ om runtime deploy --specs "basedir=/some/path"`

```
# deployfile 
vars:
  - basedir=/path/to/dir
scripts:
  - name: apps/helloflask
    local: "{basedir}/."
```
